### ISSUE TITLE
Get S3/Minio storage working

### ISSUE THREAD

**Issue by Gordonei** [cityofcapetown/Data-Portal#2]
To help things scale, the data should be going into a separate storage service. The repo currently spins up a separate Minio docker container to develop against. The idea would be that the CKAN would store all of it's data in the standalone Minio.

I tried two extensions:
* [s3-filestore](https://github.com/okfn/ckanext-s3filestore)
* [s3-resources](https://github.com/datagovsg/ckanext-s3-resources)

In both cases, I thought I was supplying sane config values, but who knows?

Both are bombing out with a fairly generic error like this in the logs:
```
Exception happened during processing of request from ('192.168.192.1', 35958)
Traceback (most recent call last):
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 1068, in process_request_in_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
```

**Comment by Gordonei** [comment]
Addressed in [this commit](https://github.com/cityofcapetown/Data-Portal/commit/7f9c138fcb1d7eaa0577fac80f74eedb3482a5d5), [this commit](https://github.com/cityofcapetown/Data-Portal/commit/158e79910108f71e8aa8b0f443065b57b15d63c9) and [this one](https://github.com/cityofcapetown/Data-Portal/commit/b1b2c50882472a43b34d9390e3c8e4d5589bfa54).

Turned out I was loading in an odd version of the extension that was trying to do strange things.
